<a href="https://colab.research.google.com/github/JBCn420/janos-dev.github.io/blob/main/carfactory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CreateDB

In [ ]:
import pandas as pd
import duckdb
import numpy as np

alkatresz_adatok = {
    'part_id': range(1001, 1031),
    'part_name': [
        'Féktárcsa Első', '  fékbetét készlet  ', 'Olajszűrő', 'Légszűrő', 'Gyújtógyertya',
        'Vezérműszíj', 'Vízpumpa', 'Generátor szíj', 'AKKUMULÁTOR 74AH', 'Önindító',
        'Lengéscsillapító Első', 'Lengőkar bal', 'Kerékcsapágy', 'Kormányösszekötő', 'Féltengely csukló',
        'Kuplung készlet', 'Kettőstömegű lendkerék', 'Kipufogó dob', 'Katalizátor', 'Lambda szonda',
        'Hűtőradiátor', 'Termosztát', 'Fűtőmotor', 'Xenon izzó', 'LED nappali fény',
        'Ablaktörlő lapát', 'Fagyálló hűtőfolyadék', 'Motorolaj 5W30', 'Váltóolaj', 'Fékfolyadék'
    ],
    'category': [
        'Fékrendszer', 'fekrendszer', 'Szerviz', 'szerviz', 'Motor',
        'Motor', 'Motor', 'Motor', 'Elektromosság', 'Elektromosság',
        'Futómű', 'Futómű', 'Futómű', 'Futómű', 'Hajtás',
        'Hajtás', 'Hajtás', 'Kipufogó', 'Kipufogó', 'Motor',
        'Hűtés', 'Hűtés', 'Elektromosság', 'Világítás', 'Világítás',
        'Karosszéria', 'Folyadékok', 'Folyadékok', 'Folyadékok', 'Folyadékok'
    ],
    'price_eur': [
        45.0, 32.5, 12.0, 15.0, 8.5, 55.0, 42.0, 18.0, 95.0, 120.0,
        65.0, 48.0, 35.0, 22.0, 40.0, 180.0, 450.0, 85.0, 220.0, 65.0,
        90.0, 25.0, 75.0, 50.0, 30.0, 15.0, 10.0, 40.0, 28.0, 12.0
    ],
    'stock_quantity': [
        12, 25, 50, 45, 100, 8, 5, 15, 10, 3,
        14, 6, 20, 18, 4, 2, 1, 5, 2, 7,
        4, 12, 3, 20, 35, 60, 100, 80, 25, 40
    ],
    'supplier': [
        'Bosch', 'Brembo', 'Mann-Filter', 'Mann-Filter', 'NGK',
        'Gates', None, 'Conti', 'Varta', 'Bosch',
        'Monroe', 'Lemförder', 'SKF', 'TRW', 'LÖBRO',
        'LUK', 'Sachs', 'Walker', 'Bosch', 'Denso',
        'Nissens', 'Behr', 'Valeo', 'Osram', 'Philips',
        'Valeo', 'Castrol', 'Castrol', 'Mobil1', 'Ate'
    ]
}

# Beiktatunk pár hiányzó árat is (NULL értékek)
df_parts = pd.DataFrame(alkatresz_adatok)
df_parts.loc[2, 'price_eur'] = np.nan # Olajszűrő ára eltűnik
df_parts.loc[6, 'price_eur'] = np.nan # Vízpumpa ára eltűnik
df_parts.to_csv('alkatresz_keszlet.csv', index=False)

print("✅ 'Koszos' tábla létrehozva!")

✅ 'Koszos' tábla létrehozva!

In [ ]:
import pandas as pd

# Gyártói adatok szándékos duplikációval
# A 1001 és a 1005 kétszer fog szerepelni a 30 sor között
part_ids_hibas = [
    1001, 1001, 1003, 1004, 1005, 1005, 1007, 1008, 1009, 1010,
    1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020,
    1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030
]

gyarto_adatok = {
    'part_id': part_ids_hibas,
    'origin_country': [
        'Németország', 'Németország', 'Németország', 'Németország', 'Japán',
        'Japán', 'Svédország', 'Németország', 'Németország', 'Németország',
        'USA', 'Németország', 'Svédország', 'Németország', 'Németország',
        'Németország', 'Németország', 'USA', 'Németország', 'Japán',
        'Dánia', 'Németország', 'Franciaország', 'Németország', 'Hollandia',
        'Franciaország', 'Nagy-Britannia', 'Nagy-Britannia', 'USA', 'Németország'
    ],
    'warranty_years': [2, 2, 1, 1, 3, 3, 2, 1, 3, 2, 2, 2, 2, 2, 2, 3, 3, 2, 5, 2, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2]
}

df_manufacturers = pd.DataFrame(gyarto_adatok)

# Mentés a content mappába
df_manufacturers.to_csv('gyartok.csv', index=False)

print("✅ A 30 soros gyártói tábla (df_manufacturers) elkészült (szándékos duplikációkkal: 1001, 1005)!")
df_manufacturers.head(10)

✅ A 30 soros gyártói tábla (df_manufacturers) elkészült (szándékos duplikációkkal: 1001, 1005)!

   part_id origin_country  warranty_years
0     1001    Németország               2
1     1001    Németország               2
2     1003    Németország               1
3     1004    Németország               1
4     1005          Japán               3
5     1005          Japán               3
6     1007     Svédország               2
7     1008    Németország               1
8     1009    Németország               3
9     1010    Németország               2

In [ ]:
import pandas as pd

# Országos márkaadatok (30 sor, koszos adatokkal)
marka_adatok = {
    'origin_country': [
        'Németország', 'németorszag', ' Olaszország ', 'Japán', 'USA',
        'svédország', 'Dánia', 'Franciaország', 'Hollandia', 'Nagy-Britannia',
        'Németország', 'németorszag', ' Olaszország ', 'Japán', 'USA',
        'svédország', 'Dánia', 'Franciaország', 'Hollandia', 'Nagy-Britannia',
        'Németország', 'németorszag', ' Olaszország ', 'Japán', 'USA',
        'svédország', 'Dánia', 'Franciaország', 'Hollandia', 'Nagy-Britannia'
    ],
    'brand_name': [
        'Bosch', 'Continental', 'Brembo', 'Denso', 'Gates',
        'SKF', 'Nissens', 'Valeo', 'Philips', 'Castrol',
        'Hella', 'ZF', 'Magneti Marelli', 'NGK', 'Monroe',
        'Haldex', 'Danfoss', 'Michelin', 'NXP', 'Lucas',
        'Mahle', 'Behr', 'Pirelli', 'Aisin', 'TRW',
        'Autoliv', 'Grundfos', 'Motul', 'TomTom', 'Delphi'
    ],
    'ceo_name': [
        'Dr. Stefan Hartung', 'Nikolai Setzer', 'Matteo Tiraboschi', 'Shinnosuke Hayashi', 'Ivo Jurek',
        'Rickard Gustafson', 'Paulus M. Goedane', 'Christophe Périllat', 'Roy Jakobs', 'Murray Auchincloss',
        'Rolf Breidenbach', 'Holger Klein', 'Arvin Power', 'Takeshi Kawai', 'George Galliers',
        'Mats Carlsson', 'Kim Fausing', 'Florent Menegaux', 'Kurt Sievers', 'Marc Robinson',
        'Arnd Franz', 'Michael Steiner', 'Marco Tronchetti', 'Kiyotaka Ise', 'John C. Smith',
        'Mikael Bratt', 'Mads Nipper', 'Arnaud Laire', 'Harold Goddijn', 'Kevin Clark'
    ]
}

df_brands = pd.DataFrame(marka_adatok)
df_brands.to_csv('orszag_markak.csv', index=False)

print("✅ Harmadik tábla (df_brands) létrehozva és elmentve: orszag_markak.csv")
print("Figyelem: Az origin_country oszlop tisztításra szorul!")

✅ Harmadik tábla (df_brands) létrehozva és elmentve: orszag_markak.csv
Figyelem: Az origin_country oszlop tisztításra szorul!

# DB megjelenítés és rosz adatok számlálása

In [ ]:
import duckdb

# A legegyszerűbb lekérdezés: "Válassz ki mindent az alkatrész táblából"
query_all = "SELECT * FROM df_parts"

# Futtatás és az eredmény megjelenítése
df_eredmeny = duckdb.query(query_all).to_df()
df_eredmeny

,part_id,part_name,category,price_eur,stock_quantity,supplier
0,1001,Féktárcsa Első,Fékrendszer,45.0,12,Bosch
1,1002,fékbetét készlet,fekrendszer,32.5,25,Brembo
2,1003,Olajszűrő,Szerviz,NaN,50,Mann-Filter
3,1004,Légszűrő,szerviz,15.0,45,Mann-Filter
4,1005,Gyújtógyertya,Motor,8.5,100,NGK
5,1006,Vezérműszíj,Motor,55.0,8,Gates
6,1007,Vízpumpa,Motor,NaN,5,None
7,1008,Generátor szíj,Motor,18.0,15,Conti
8,1009,AKKUMULÁTOR 74AH,Elektromosság,95.0,10,Varta
9,1010,Önindító,Elektromosság,120.0,3,Bosch
10,1011,Lengéscsillapító Első,Futómű,65.0,14,Monroe
11,1012,Lengőkar bal,Futómű,48.0,6,Lemförder
12,1013,Kerékcsapágy,Futómű,35.0,20,SKF
13,1014,Kormányösszekötő,Futómű,22.0,18,TRW
14,1015,Féltengely csukló,Hajtás,40.0,4,LÖBRO
15,1016,Kuplung készlet,Hajtás,180.0,2,LUK
16,1017,Kettőstömegű lendkerék,Hajtás,450.0,1,Sachs
17,1018,Kipufogó dob,Kipufogó,85.0,5,Walker
18,1019,Katalizátor,Kipufogó,220.0,2,Bosch
19,1020,Lambda szonda,Motor,65.0,7,Denso
20,1021,Hűtőradiátor,Hűtés,90.0,4,Nissens
21,1022,Termosztát,Hűtés,25.0,12,Behr
22,1023,Fűtőmotor,Elektromosság,75.0,3,Valeo
23,1024,Xenon izzó,Világítás,50.0,20,Osram
24,1025,LED nappali fény,Világítás,30.0,35,Philips
25,1026,Ablaktörlő lapát,Karosszéria,15.0,60,Valeo
26,1027,Fagyálló hűtőfolyadék,Folyadékok,10.0,100,Castrol
27,1028,Motorolaj 5W30,Folyadékok,40.0,80,Castrol
28,1029,Váltóolaj,Folyadékok,28.0,25,Mobil1
29,1030,Fékfolyadék,Folyadékok,12.0,40,Ate

In [ ]:
import duckdb

# Megszámoljuk, hol hány NULL érték van
query_audit = """
SELECT
    COUNT(*) as osszes_sor,
    COUNT(part_name) as kitoltott_nevek,
    COUNT(*) - COUNT(part_name) as hianyzo_nevek,
    COUNT(price_eur) as kitoltott_arak,
    COUNT(*) - COUNT(price_eur) as hianyzo_arak,
    COUNT(*) - COUNT(supplier) as hianyzo_beszallitok
FROM df_parts
"""
duckdb.query(query_audit).to_df()

,osszes_sor,kitoltott_nevek,hianyzo_nevek,kitoltott_arak,hianyzo_arak,hianyzo_beszallitok
0,30,30,0,28,2,1

# Hibás sorok kiiratása NULL/DISTINCT/ROW_NUMBER

In [ ]:
import duckdb

#------------Megnézzük szerepelnek e NULL értékek majd kiszürjük őket--------------

# A legegyszerűbb lekérdezés: "Válassz ki mindent az alkatrész táblából"
query_all = """
SELECT *,
    CASE
        WHEN part_name IS NULL OR price_eur IS NULL OR supplier IS NULL
        THEN '⚠️ HIÁNYOS ADAT'
        ELSE '✅ RENDBEN'
    END AS statusz
FROM df_parts
ORDER BY statusz ASC -- Így a hibásak kerülnek előre
"""

# Futtatás és az eredmény megjelenítése
df_eredmeny = duckdb.query(query_all).to_df()
df_eredmeny

,part_id,part_name,category,price_eur,stock_quantity,supplier,statusz
0,1003,Olajszűrő,Szerviz,NaN,50,Mann-Filter,⚠️ HIÁNYOS ADAT
1,1007,Vízpumpa,Motor,NaN,5,None,⚠️ HIÁNYOS ADAT
2,1001,Féktárcsa Első,Fékrendszer,45.0,12,Bosch,✅ RENDBEN
3,1025,LED nappali fény,Világítás,30.0,35,Philips,✅ RENDBEN
4,1005,Gyújtógyertya,Motor,8.5,100,NGK,✅ RENDBEN
5,1006,Vezérműszíj,Motor,55.0,8,Gates,✅ RENDBEN
6,1002,fékbetét készlet,fekrendszer,32.5,25,Brembo,✅ RENDBEN
7,1008,Generátor szíj,Motor,18.0,15,Conti,✅ RENDBEN
8,1009,AKKUMULÁTOR 74AH,Elektromosság,95.0,10,Varta,✅ RENDBEN
9,1004,Légszűrő,szerviz,15.0,45,Mann-Filter,✅ RENDBEN
10,1011,Lengéscsillapító Első,Futómű,65.0,14,Monroe,✅ RENDBEN
11,1012,Lengőkar bal,Futómű,48.0,6,Lemförder,✅ RENDBEN
12,1013,Kerékcsapágy,Futómű,35.0,20,SKF,✅ RENDBEN
13,1014,Kormányösszekötő,Futómű,22.0,18,TRW,✅ RENDBEN
14,1015,Féltengely csukló,Hajtás,40.0,4,LÖBRO,✅ RENDBEN
15,1016,Kuplung készlet,Hajtás,180.0,2,LUK,✅ RENDBEN
16,1017,Kettőstömegű lendkerék,Hajtás,450.0,1,Sachs,✅ RENDBEN
17,1018,Kipufogó dob,Kipufogó,85.0,5,Walker,✅ RENDBEN
18,1019,Katalizátor,Kipufogó,220.0,2,Bosch,✅ RENDBEN
19,1020,Lambda szonda,Motor,65.0,7,Denso,✅ RENDBEN
20,1021,Hűtőradiátor,Hűtés,90.0,4,Nissens,✅ RENDBEN
21,1022,Termosztát,Hűtés,25.0,12,Behr,✅ RENDBEN
22,1023,Fűtőmotor,Elektromosság,75.0,3,Valeo,✅ RENDBEN
23,1024,Xenon izzó,Világítás,50.0,20,Osram,✅ RENDBEN
24,1030,Fékfolyadék,Folyadékok,12.0,40,Ate,✅ RENDBEN
25,1026,Ablaktörlő lapát,Karosszéria,15.0,60,Valeo,✅ RENDBEN
26,1027,Fagyálló hűtőfolyadék,Folyadékok,10.0,100,Castrol,✅ RENDBEN
27,1028,Motorolaj 5W30,Folyadékok,40.0,80,Castrol,✅ RENDBEN
28,1029,Váltóolaj,Folyadékok,28.0,25,Mobil1,✅ RENDBEN
29,1010,Önindító,Elektromosság,120.0,3,Bosch,✅ RENDBEN

In [ ]:
import duckdb

# Ellenőrizzük mindhárom táblát az egyedi kulcsaik alapján
query_triple_check = """
SELECT 'Alkatrészek' as tabla, COUNT(part_id) - COUNT(DISTINCT part_id) as duplikalt_id_szam FROM df_parts
UNION ALL
SELECT 'Gyártók', COUNT(part_id) - COUNT(DISTINCT part_id) FROM df_manufacturers
UNION ALL
SELECT 'Márkák', COUNT(brand_name) - COUNT(DISTINCT brand_name) FROM df_brands
"""

duckdb.query(query_triple_check).to_df()

         tabla  duplikalt_id_szam
0  Alkatrészek                  0
1      Gyártók                  2
2       Márkák                  0

In [ ]:
import duckdb

# Ellenőrizzük egy tablaban a DISTINCet - ez azt jelenti hogy ezekben NINCSEN duplikacio-------------------

query_tabla_check = """

SELECT
COUNT(DISTINCT part_id) as NEMduplikalt_part_id_szamok
FROM df_manufacturers

"""

duckdb.query(query_tabla_check).to_df()

   NEMduplikalt_part_id_szamok
0                           28

In [ ]:
import duckdb

# Megkeressük azokat a sorokat, amiknek az ID-ja többször szerepel
query_teljes_duplo = """
SELECT *
FROM df_manufacturers
WHERE part_id IN (
    SELECT part_id
    FROM df_manufacturers
    GROUP BY part_id
    HAVING COUNT(*) > 1
)
ORDER BY part_id
"""

df_duplak = duckdb.query(query_teljes_duplo).to_df()
df_duplak

   part_id origin_country  warranty_years
0     1001    Németország               2
1     1001    Németország               2
2     1005          Japán               3
3     1005          Japán               3

In [ ]:
import duckdb

# SQL megoldás: Csoportosítunk ID szerint, és minden csoportból csak egyet tartunk meg
query_clean_sql = """
SELECT part_id, origin_country, warranty_years
FROM df_manufacturers
GROUP BY part_id, origin_country, warranty_years
"""

df_manufacturers_clean = duckdb.query(query_clean_sql).to_df()
print(f"Tisztított sorok száma: {len(df_manufacturers_clean)}")
df_manufacturers_clean.head()

Tisztított sorok száma: 28

   part_id origin_country  warranty_years
0     1003    Németország               1
1     1004    Németország               1
2     1008    Németország               1
3     1009    Németország               3
4     1010    Németország               2

In [ ]:
import duckdb

# A "profi" tisztító lekérdezés A WHERE sorrend 1 kiirja az egyediket a 2 kiirja a duplikaltakat
query_row_number = """
SELECT
    part_id,
    origin_country,
    warranty_years
FROM (
    SELECT *,
        ROW_NUMBER() OVER(PARTITION BY part_id ORDER BY part_id) as sorrend
    FROM df_manufacturers
)
WHERE sorrend = 1
ORDER BY part_id
"""

# Futtatás és mentés
df_manufacturers_clean = duckdb.query(query_row_number).to_df()

print(f"✅ Tisztítás kész! Sorok száma: {len(df_manufacturers_clean)}")
df_manufacturers_clean.head()

✅ Tisztítás kész! Sorok száma: 2

   part_id origin_country  warranty_years
0     1001    Németország               2
1     1005          Japán               3

# Megtisztitott adatbazis mentése

In [ ]:
import duckdb

# SQL-alapú tisztítás: A DISTINCT kulcsszóval kiszűrjük az egyedi sorokat
# és egyből az eredményt tesszük be a df_manufacturers_clean változóba
query_tisztitas = """
SELECT DISTINCT * FROM df_manufacturers
ORDER BY part_id
"""

# A lekérdezés futtatása és Pandas DataFrame-mé alakítása
df_manufacturers_clean = duckdb.query(query_tisztitas).to_df()

# Ellenőrzés SQL-lel: Megszámoljuk az egyedi sorokat
query_count = "SELECT COUNT(*) FROM df_manufacturers_clean"
tiszta_szam = duckdb.query(query_count).fetchone()[0]

print(f"✅ SQL-lel megtisztítva! Maradt összesen: {tiszta_szam} sor.")

# Mentés (ezt Pythonnal csináljuk, mert az a legegyszerűbb fájlkezelés)
df_manufacturers_clean.to_csv('gyartok_tisztitott.csv', index=False)

df_manufacturers_clean.head()

✅ SQL-lel megtisztítva! Maradt összesen: 28 sor.

   part_id origin_country  warranty_years
0     1001    Németország               2
1     1003    Németország               1
2     1004    Németország               1
3     1005          Japán               3
4     1007     Svédország               2

# Lekérdezések

JOIN

In [ ]:
import duckdb

# A legegyszerűbb lekérdezés: "Válassz ki mindent az alkatrész táblából"
query_all = """

SELECT
   DISTINCT p.part_name,
    p.price_eur,
    m.origin_country,
    m.warranty_years

FROM df_parts p
LEFT JOIN df_manufacturers_clean m ON p.part_id = m.part_id
LEFT JOIN df_brands b ON m.origin_country = b.origin_country
WHERE p.price_eur > 50
ORDER BY p.price_eur DESC

"""

# Futtatás és az eredmény megjelenítése
df_eredmeny = duckdb.query(query_all).to_df()
df_eredmeny

                 part_name  price_eur origin_country  warranty_years
0   Kettőstömegű lendkerék      450.0    Németország               3
1              Katalizátor      220.0    Németország               5
2          Kuplung készlet      180.0    Németország               3
3                 Önindító      120.0    Németország               2
4         AKKUMULÁTOR 74AH       95.0    Németország               3
5             Hűtőradiátor       90.0          Dánia               2
6             Kipufogó dob       85.0            USA               2
7                Fűtőmotor       75.0  Franciaország               2
8    Lengéscsillapító Első       65.0            USA               2
9            Lambda szonda       65.0          Japán               2
10             Vezérműszíj       55.0           None            <NA>

In [ ]:
import duckdb

# A legegyszerűbb lekérdezés: "Válassz ki mindent az alkatrész táblából"
query_all = """

SELECT  p.part_name as alkatrész, m.origin_country as Származási_ország
FROM df_parts p
LEFT JOIN df_manufacturers_clean m ON p.part_id = m.part_id
WHERE m.origin_country = 'Svédország'

"""

# Futtatás és az eredmény megjelenítése
df_eredmeny = duckdb.query(query_all).to_df()
df_eredmeny

      alkatrész Származási_ország
0      Vízpumpa        Svédország
1  Kerékcsapágy        Svédország

In [ ]:
import duckdb

# COUNT(*) kiirja hogy kétszer szerepelne svédország"
query_all = """

SELECT COUNT(*)
FROM df_parts p
LEFT JOIN df_manufacturers_clean m ON p.part_id = m.part_id
WHERE m.origin_country = 'Svédország'

"""

# Futtatás és az eredmény megjelenítése
df_eredmeny = duckdb.query(query_all).to_df()
df_eredmeny

 DROPBOX

In [ ]:
#@title 🔍 Alkatrész kereső ország szerint
valasztott_orszag = "Németország" #@param ["Németország", "Svédország", "USA", "Franciaország", "Japán"]

# Az SQL lekérdezés egyszerűen használja a fenti változót
query = f"""
SELECT p.part_name, p.price_eur, m.origin_country
FROM df_parts p
JOIN df_manufacturers_clean m ON p.part_id = m.part_id
WHERE m.origin_country = '{valasztott_orszag}'
"""

# Futtatás és kiírás
df_eredmeny = duckdb.query(query).to_df()
df_eredmeny

                 part_name  price_eur origin_country
0           Féktárcsa Első       45.0    Németország
1                Olajszűrő        NaN    Németország
2                 Légszűrő       15.0    Németország
3           Generátor szíj       18.0    Németország
4         AKKUMULÁTOR 74AH       95.0    Németország
5                 Önindító      120.0    Németország
6             Lengőkar bal       48.0    Németország
7         Kormányösszekötő       22.0    Németország
8        Féltengely csukló       40.0    Németország
9          Kuplung készlet      180.0    Németország
10  Kettőstömegű lendkerék      450.0    Németország
11             Katalizátor      220.0    Németország
12              Termosztát       25.0    Németország
13              Xenon izzó       50.0    Németország
14             Fékfolyadék       12.0    Németország

In [ ]:
import pandas as pd
import duckdb
import ipywidgets as widgets
from IPython.display import display, clear_output

# 1. Kigyűjtjük az egyedi országokat a menühöz
countries = df_manufacturers_clean['origin_country'].unique().tolist()
countries.sort() # Legyenek ABC sorrendben

# 2. Létrehozzuk a legördülő menüt (Dropdown)
dropdown = widgets.Dropdown(
    options=countries,
    description='Ország:',
    disabled=False,
)

# 3. Létrehozunk egy kimeneti ablakot a táblázatnak
output = widgets.Output()

# 4. A függvény, ami lefut, ha váltasz a menüben
def on_change(change):
    if change['type'] == 'change' and change['name'] == 'value':
        with output:
            clear_output(wait=True) # Törli az előző táblázatot
            selected_country = change['new']

            # Az SQL lekérdezés, amibe beillesztjük a választott országot
            query = f"""
            SELECT p.part_name, p.price_eur, m.origin_country
            FROM df_parts p
            JOIN df_manufacturers_clean m ON p.part_id = m.part_id
            WHERE m.origin_country = '{selected_country}'
            """

            eredmeny = duckdb.query(query).to_df()
            display(eredmeny)

# Figyeljük a változást
dropdown.observe(on_change)

# Megjelenítjük a menüt és a táblázat helyét
display(dropdown)
display(output)

# Az első indításhoz "megpöccintjük" a függvényt
on_change({'type': 'change', 'name': 'value', 'new': countries[0]})

Dropdown(description='Ország:', options=('Dánia', 'Franciaország', 'Hollandia', 'Japán', 'Nagy-Britannia', 'Né…

Output()